const Event = require('../Structures/Construction/Event');
const {
    MessageEmbed
} = require(`discord.js`)
module.exports = class extends Event {
    async run(error) {
        let codes = {
            4000: `Unknown error: Мы не уверены, что пошло не так. Попробовать переподключиться?`,
            4001: `Unknown opcode: Вы отправили неверный код операции шлюза или недопустимые данные для кода операции. Не делай этого!`,
            4002: `Decode error: Вы отправили нам недопустимые данные. Не делай этого!`,
            4003: `Not authenticated: Вы отправили нам полезные данные до идентификации.`,
            4004: `Authentication failed: токен учетной записи, отправленный с данными идентификации, неверен.`,
            4005: `Already authenticated: Вы отправили более одной полезной нагрузки идентификации. Не делай этого!`,
            4006: `Session no longer valid	Your session is no longer valid.`,
            4007: `Invalid seq: Последовательность, отправленная при возобновлении сеанса, была недопустимой. Переподключитесь и начните новый сеанс.`,
            4008: `Rate limitedWoah nelly: Вы слишком быстро отправляете нам полезные данные. Замедли это! Вы будете отключены при получении этого сообщения.`,
            4009: `Session timed out: Время ожидания сеанса истекло. Переподключитесь и начните новый.`,
            4010: `Invalid shard: Вы отправили нам неверный шард при идентификации.`,
            4011: `Sharding required: сеанс обрабатывал бы слишком много гильдий - вам необходимо выполнить шардинг для подключения.`,
            4012: `Invalid API version: Вы отправили неверную версию для шлюза.`,
            4013: `Invalid intent (s) Вы отправили недопустимое намерение для намерения шлюза. Возможно, вы неправильно рассчитали побитовое значение.`,
            4014: `Disallowed intent (s) Вы отправили запрещенное намерение для намерения шлюза. Возможно, вы пытались указать намерение, которое не включено или не включено в белый список.`,
            4015: `Voice server crashed The server crashed.Our bad!Try resuming.`,
            4016: `Unknown encryption mode We didn 't recognize your encryption.`,
            10001: `Unknown account`,
            10002: `Unknown application`,
            10003: `Unknown channel`,
            10004: `Unknown guild`,
            10005: `Unknown integration`,
            10006: `Unknown invite`,
            10007: `Unknown member`,
            10008: `Unknown message`,
            10009: `Unknown permission overwrite `,
            10010: `Unknown provider `,
            10011: `Unknown role `,
            10012: `Unknown token `,
            10013: `Unknown user `,
            10014: `Unknown emoji `,
            10015: `Unknown webhook `,
            10026: `Unknown ban `,
            10027: `Unknown SKU `,
            10028: `Unknown Store Listing `,
            10029: `Unknown entitlement `,
            10030: `Unknown build `,
            10031: `Unknown lobby `,
            10032: `Unknown branch `,
            10036: `Unknown redistributable `,
            10057: `Unknown guild template `,
            20001: `Bots cannot use this endpoint `,
            20002: `Only bots can use this endpoint `,
            20022: `This message cannot be edited due to announcement rate limits `,
            20028: `The channel you are writing has hit the write rate limit `,
            30001: `Maximum number of guilds reached(100) `,
            30002: `Maximum number of friends reached(1000) `,
            30003: `Maximum number of pins reached for the channel(50) `,
            30005: `Maximum number of guild roles reached(250) `,
            30007: `Maximum number of webhooks reached(10) `,
            30010: `Maximum number of reactions reached(20) `,
            30013: `Maximum number of guild channels reached(500) `,
            30015: `Maximum number of attachments in a message reached(10) `,
            30016: `Maximum number of invites reached(1000) `,
            40001: `Unauthorized.Provide a valid token and try again `,
            40002: `You need to verify your account in order to perform this action `,
            40005: `Request entity too large.Try sending something smaller in size `,
            40006: `This feature has been temporarily disabled server - side `,
            40007: `The user is banned from this guild `,
            40033: `This message has already been crossposted `,
            50001: `Missing access `,
            50002: `Invalid account type `,
            50003: `Cannot execute action on a DM channel `,
            50004: `Guild widget disabled `,
            50005: `Cannot edit a message authored by another user `,
            50006: `Cannot send an empty message `,
            50007: `Cannot send messages to this user `,
            50008: `Cannot send messages in a voice channel `,
            50009: `Channel verification level is too high for you to gain access `,
            50010: `OAuth2 application does not have a bot `,
            50011: `OAuth2 application limit reached `,
            50012: `Invalid OAuth2 state `,
            50013: `You lack permissions to perform that action `,
            50014: `Invalid authentication token provided `,
            50015: `Note was too long `,
            50016: `Provided too few or too many messages to delete.Must provide at least 2 and fewer than 100 messages to delete `,
            50019: `A message can only be pinned to the channel it was sent in `,
            50020: `Invite code was either invalid or taken `,
            50021: `Cannot execute action on a system message `,
            50024: `Cannot execute action on this channel type `,
            50025: `Invalid OAuth2 access token provided `,
            50033: "Invalid Recipient(s)",
            50034: `A message provided was too old to bulk delete `,
            50035: `Invalid form body(returned for both application / json and multipart / form - data bodies),or invalid Content - Type provided `,
            50036: `An invite was accepted to a guild the application 's bot is not in `,
            50041: `Invalid API version provided `,
            50074: `Cannot delete a channel required for Community guilds `,
            90001: `Reaction was blocked `,
            130000: `API resource is currently overloaded.Try again a little later `
        }
        return this.Main.channels.cache.get('772907942718341130').send(new MessageEmbed().setTitle(codes[error.code]).setDescription(`message: ${error.message}\npath: ${error.path}`).setTitle(error.name).setURL(error.path).setTimestamp().setFooter(error.method))
    }
}